### ISSUE TITLE
Ability to see current timestamp 

### ISSUE THREAD

**Issue by Redhawk2000** [Tautulli/Tautulli-Remote#101]
It used to be possible on the previous version to see the timestamp of where someone was in the movie like the first one in the image below showed 112:01. With the current one I have to tap to see that detail. And frankly it would be even better if it put in in hour:minute format instead of just minutes.

![Screenshot_20200602-202341123_1](https://user-images.githubusercontent.com/18142543/111010026-48202800-8363-11eb-830e-23af0246bc58.jpg)

**Comment by TheMeanCanEHdian** [comment]
The cards are intended to provide data at a glance and it was decided that a computed "time left" was more valuable with the space limitations of the card. This is why the full timestamp was added to the activity details sheet.

The `minute:second` format of the timestamp is following the current Tautulli behavior. I try not to heavily deviate from the Tautulli UI except where it doesn't translate well to mobile.

**Comment by TheMeanCanEHdian** [comment]
Feel free to use the Feature Request template for something like a setting to toggle if the card shows an ETA or the progress/timestamp. Then people can at least thumbs it up and if enough people want it it can be considered.
