### ISSUE TITLE
Ability to Re-Order Servers

### ISSUE THREAD

**Issue by meestark** [Tautulli/Tautulli-Remote#102]
**Is your feature request related to a problem? Please describe.**
When using multiple servers, it would be nice to be able to re-order the way they display without having to remove/re-add the accounts.

**Describe the solution you'd like**
On the settings page, have the ability to re-order, either via a drag and droppable element, or a priority level set by digit.

**Describe alternatives you've considered**
The only alternative seems to be removing and readding the accounts in the order you want them.

**Additional context**
N/A

**Comment by TheMeanCanEHdian** [comment]
This has been added and will be available in the next release.

**Comment by TheMeanCanEHdian** [comment]
This is available in 2.7.0.
