### ISSUE TITLE
ETA Time

### ISSUE THREAD

**Issue by mattm3** [Tautulli/Tautulli-Remote#103]
**Describe the bug**
When checking the ETA time, if it's after 12am the time displays as 0:7 whereas in the old app it shows as 12:07

**To Reproduce**
1. Go to 'Activity'
2. Tap on the media you have playing
3. If the time is after 12am it will display as explain above.

**Expected behavior**
The time to display how it did in the old app.

**Screenshots**

NEW APP

![Screenshot_20210313-234646](https://user-images.githubusercontent.com/28574604/111052923-81d25b00-8457-11eb-9206-d8d7d36ad1e8.jpg)

OLD APP

![Screenshot_20210313-234713_Tautulli Remote](https://user-images.githubusercontent.com/28574604/111052931-8ac32c80-8457-11eb-9767-610369f3b071.jpg)

**Tautulli Info (please complete the following information):**
 - Mobile Device: Samsung Galaxy S10+
 - Mobile OS: Android 11
 - Tautulli Remote Version: 2.4.4
 - Tautulli Version: 2.6.8

**Additional context**
N/A

**Comment by TheMeanCanEHdian** [comment]
In order to follow the main Tautulli UI, I will update this to add a leading 0 but I will not change it to say 12. 24 hour time is currently being used so 12 would be incorrect.

**Comment by TheMeanCanEHdian** [comment]
I've opened #104 to address using the same format that is set in Tautulli.

**Comment by TheMeanCanEHdian** [comment]
This was implemented in version 2.4.5.
