### ISSUE TITLE
Add artwork to notifications

### ISSUE THREAD

**Issue by MRFU510N88** [Tautulli/Tautulli-Remote#106]
**Is your feature request related to a problem? Please describe.**
Before the android app change I'm sure there was images/album art on the phone notifications. Doesnt seem to be the case now.

**Describe the solution you'd like**
Android notifications that have art, for example if the notification was for a movie started playing, the movie art would be the displayed image.

Android 10 has the ability for notification images that can be expanded and enlarged when swiped down in the notification tray.

**Comment by TheMeanCanEHdian** [comment]
I've done some work on this and there is a pretty large underlying issue with implementing this feature.

Android only displays a small square icon for these notifications. Images from Tautulli are not going to be always fit in a square, and this results in a pretty unattractive look for these notifications.

![image](https://user-images.githubusercontent.com/16025103/112202958-5f270b80-8be8-11eb-9f31-e4239236c0de.png)

As long as this limitation exists (or no better options come along) I do not want to add images to the notifications.

**Comment by MRFU510N88** [comment]
Good evening,

There is another type of notification icon which the ring app utilises
perfectly. please see the attached images.

In short if you swipe down on the notification it expands to  provide more
information and a larger image this would look great if you could implement
it.

Thanks

James.

**Comment by TheMeanCanEHdian** [comment]
Your images don't appear to have been shared.

**Comment by MRFU510N88** [comment]
Hopefully these show:

![20210323_230537](https://user-images.githubusercontent.com/35142900/112230146-4a6c6700-8c2c-11eb-850d-13ecabb796ba.jpg)
![20210323_230450](https://user-images.githubusercontent.com/35142900/112230157-4fc9b180-8c2c-11eb-97d8-0015faedb6f9.jpg)

**Comment by TheMeanCanEHdian** [comment]
This appears to be some kind of custom notification they are doing.  Android's native notification types (including an expanding image notification) are [found here](https://developer.android.com/training/notify-user/expanded#image-style).

The end result is that you still don't see the whole image and now long text cannot be expanded.

![qemu-system-x86_64_2021-03-23_15-32-10](https://user-images.githubusercontent.com/16025103/112231260-c2c33000-8c0c-11eb-8b43-f61a544291c0.png)

**Comment by MRFU510N88** [comment]
Its definately an improvement on the small icon. What is the source image a banner or poster? Could the source image not be cropped based on height and aligned to the right?

**Comment by TheMeanCanEHdian** [comment]
What you see above is a full poster being given to the notification that it then crops to fit the bounds of what the notification shows. There is no adjustment of image size or location.

The fact that this type of notification makes long text unexpandable rules out its use. I'm not willing to sacrifice seeing the main content of the notification for cropped artwork.

**Comment by MRFU510N88** [comment]
If you compare it to the notification style i shared an image of it is visually completely different. Yours fills the entire notification window. What I am suggesting is that the poster be cropped based on height therefore it will look more like the one I showed with plenty of room for text?

**Comment by TheMeanCanEHdian** [comment]
The issue is that notification is not one of the [notification types Android provides](https://developer.android.com/training/notify-user/expanded#image-style). It looks like something we would need to build/design our own notification for (this also then presents extra work for future iOS builds).

I am not seeing the value in investing the time to create that when it does not add critical information to the notification.

**Comment by MRFU510N88** [comment]
It may not add critical information but it is much more aesthetically pleasing and used to support text as a visual reference. 

The same can be said for album art or movie posters, its not a necessity but it adds a sense of depth and a visual/photographic reference to the content. 

I am also under the impression that the notification would need to be created from scratch to suit its purpose.  It is my opinion that it is a great feature idea that would be a welcome addition.

I can only request this feature and hope that you adopt it, however if I have failed to convince you of its worth the ball essentially stops with you.

Either way thank-you for your time and consideration.

**Comment by TheMeanCanEHdian** [comment]
We're discussing allowing a choice of one of the 3 notification types from Tautulli. 

However, at this time there are no plans to create custom notification layouts.

**Comment by TheMeanCanEHdian** [comment]
A setting is being added to Tautulli to customize the type of notification used. However, this choice will be from the 2 examples provided above or a 3rd no-image option. The next version of the app will honor [that setting](8da00e4c1f35d7a0f6212284b18147c69a2c844f).

There are no plans to create a custom notification type at this time.

**Comment by TheMeanCanEHdian** [comment]
This is live in the app. Currently, you need to be on the Nightly build of Tautulli for it to show up in settings.

**Comment by MRFU510N88** [comment]
I am on nightly build V2.6.10 however I do not see the setting anywhere on the tautulli remote app which has also just been updated.

**Comment by TheMeanCanEHdian** [comment]
The setting is in Tautulli and currently requires the nightly build.

**Comment by MRFU510N88** [comment]
I found it. Nice work, the larger image version is very pleasing visually its a shame it cuts off the text though. Hopefully in the future if time permits you could create a custom notification to eliminate this problem.

**Comment by MRFU510N88** [comment]
Ive had a bit of a play with the notification and noticed that when pictures/videos are played the notification image does not correlate with the file being viewed on plex nor does it change?

**Comment by TheMeanCanEHdian** [comment]
The image is sent by Tautulli. If you think there is an issue there you'll want to go to the #support channel on the discord or if you have evidence of a bug file it on the [Tautulli issues](https://github.com/Tautulli/Tautulli/issues/new/choose).
