### ISSUE TITLE
Show if show/movie was transcoded in the history section. 

### ISSUE THREAD

**Issue by Fma15** [Tautulli/Tautulli-Remote#108]
When I tap on a TV show or movie in the history section it gives me more details about it, but it doesn't show if it was transcoded or not. 

When I tap on a TV show or more I would like it to also show if it was transcoded. I would also like it to show if it was hardware or software transcoded.

**Comment by DonCaliOni** [comment]
Not sure how difficult it would be, but would be useful to also know what quality the video was transcoded to i.e. 1080p to 720p etc.

**Comment by derekn** [comment]
remote for tautulli app has this, so shouldn't be too difficulty to add. would love to see it here, it's the only reason I'm still running both apps

**Comment by TheMeanCanEHdian** [comment]
@DonCaliOni Adding video quality is not in scope for this request as the data comes from another API call and I would rather it is worked into view with the rest of the stream info. Please make a unique feature request for that.

**Comment by TheMeanCanEHdian** [comment]
Transcode decision in history details will be available in the next update.
