### ISSUE TITLE
Cannot Scan or Manually Register Device

### ISSUE THREAD

**Issue by wingman1487** [Tautulli/Tautulli-Remote#111]
**Describe the bug**
Freshly downloaded the remote today, while trying to register my Pixel 4 XL to Tautulli I receive several error popups.  Nothing is logged in the logs about it, there is just 3 entries there, 2 INFO and 1 ERROR, however the ERROR seems irrelivent to this issue.

ERROR in Logs
> Users: Failed to fetch users

To ensure everything is up to date and fresh I've....

1. Updated the Docker container running Tautulli to the latest version (2.7.0)
2. Rebuilt the container (preserving my configs)
3. Ensured that the phone app is up to date on the latest version (2.8.0)
4. Rebooted the phone for grins
5. Regenerated the registration code several times all with the same results

**Scanning QR Code**
While attempting to scan the QR Code generated by Tautulli I receive the below error on the phone app.

> QR Code Scan Failed.
> Check that the QR code you are scanning is correct

**Enter Manually**
While attempting to enter the information manually I receive the below error on the URL portion.  There isn't anything out of place with my URL, but for some reason it doesn't seem to like it.

URL Used
_http://docker-srv:8181/tautulli_

> Please enter a valid URL format

**Tautulli Info:**
 - Mobile Device: Pixel 4 XL
 - Mobile OS: Android 11
 - Tautulli Remote Version: 2.8.0
 - Tautulli Version: 2.7.0
 - Docker Image: linuxserver/tautulli:latest

**Comment by wingman1487** [comment]
This looks like an issue with it not liking the name in the URL "docker-srv", when I replaced this with an IP Address the app quit complaining about it not being a valid URL.  However, it still wouldn't register manually giving me an error in the logs...

> RegisterDevice: Failed to register device [ServerFailure]

I noticed something on the Tautulli server registration though, you can change the text in the Tautulli Address and the QR Code is auto updated, so I removed "docker-srv" and replaced it with the IP Address, QR Code updated, and was successfully scanned and registered.

All and all working, but I think there is an issue where it won't let me use my own DNS names and requiring me to use an IP Address instead.

**Comment by TheMeanCanEHdian** [comment]
> URL Used
http://docker-srv:8181/tautulli

A top-level domain is required in the address, you need `.com` or similar.
