### ISSUE TITLE
QR Code Scan Failed

### ISSUE THREAD

**Issue by swvajanyatek** [Tautulli/Tautulli-Remote#112]
I can't seem register a new device, since scanning the QR code or entering the code manually always fail. 
how do I troubleshoot?

android
tautulli remote 2.8.0

Git Branch: | master
-- | --
Git Commit Hash: | 39ad3f9047fb3f8ed7b18b1584b079a70280d37b
Configuration File: | /config/config.ini
Database File: | /config/tautulli.db \| Status
Log File: | /config/logs/tautulli.log
Backup Directory: | /config/backups
Cache Directory: | /config/cache
Export Directory: | /config/exports
Newsletter Directory: | /config/newsletters
Arguments: | ['--datadir', '/config']
Platform: | [Docker] Linux 5.6.13-100.fc30.x86_64 (#1 SMP Fri May 15 00:36:06 UTC 2020 - Debian GNU/Linux 10 buster)
System Timezone: | America/New_York (UTC-0400)
Python Version: | 3.8.8 (default, Feb 19 2021, 18:07:06) [GCC 8.3.0]

**Comment by TheMeanCanEHdian** [comment]
Github issues are for bugs and feature requests, for support please visit the Discord channel: https://tautulli.com/discord
