### ISSUE TITLE
Contact to onesignal - even when no consent given

### ISSUE THREAD

**Issue by nitrox-github** [Tautulli/Tautulli-Remote#116]
Hi!

Even without consent to onesignal data privacy, tautulli-remote makes a request to those servers, or atleast requests an IP address every 90 seconds. Maybe no data is sent, but i still feel tracked and my IP, time and device might get logged.

And whats the request to tautulli.com for? If blocked, it still works, please elaborate on both and reconsider if its really needed.

Otherwise thanks for the nice app, a donation has already been made.

Regards

**Comment by TheMeanCanEHdian** [comment]
First of all, thank you for your interest in the app and for expressing your concerns. I have addressed your questions below in detail with links to the relevant source code.

> Even without consent to onesignal data privacy, tautulli-remote makes a request to those servers, or atleast requests an IP address every 90 seconds. Maybe no data is sent, but i still feel tracked and my IP, time and device might get logged.

Tautulli Remote has a OneSignalHealthCheck function. This is a simple grab of the onesignal.com site ([seen here](https://github.com/Tautulli/Tautulli-Remote/blob/main/lib/features/onesignal/data/datasources/onesignal_data_source.dart#L40-L48)) and if the response code is 200 it returns true.

I am not sure where you are getting every 90 seconds from as this is not run at any regular intervals. Rather specific events trigger a health check. These events are:
- [When the app is first started](https://github.com/Tautulli/Tautulli-Remote/blob/6bdd5ad1ea8a865a41eb688f5ea57c825e51585f/lib/tautulli_remote.dart#L60)
- [If the OneSignal consent trigger is changed](https://github.com/Tautulli/Tautulli-Remote/blob/749747940a35964d9e2ee5375a98e04225621449/lib/features/privacy/presentation/pages/privacy_page.dart#L95-L109)
- [On the settings page if consent has been provided](https://github.com/Tautulli/Tautulli-Remote/blob/6bdd5ad1ea8a865a41eb688f5ea57c825e51585f/lib/features/settings/presentation/pages/settings_page.dart#L60)
- [When the `CHECK AGAIN` button is pressed on the OneSignal connection banner](https://github.com/Tautulli/Tautulli-Remote/blob/c6aef9c7ef9aa8362d617a178c9edfbb1ae97b13/lib/features/settings/presentation/widgets/settings_alert_banner.dart#L77-L79)
- [When the `CHECK AGAIN` button is pressed on the Wizard OneSignal page connection banner](https://github.com/Tautulli/Tautulli-Remote/blob/7391567556dcfd3aa63d34ce0b8677e290669b53/lib/features/wizard/presentation/widgets/onesignal.dart#L130-L131)

>And whats the request to tautulli.com for? If blocked, it still works

The request to tautulli.com is for[ fetching a JSON that populates the announcements page](https://github.com/Tautulli/Tautulli-Remote/blob/main/lib/features/announcements/data/datasources/announcements_data_source.dart#L21-L24). This page allows us to update users on any critical items without having to push an app update. It is highly recommended you do not block this, but as you noted, the app will continue to function without access.

**Comment by nitrox-github** [comment]
I see this when I open tautulli-remote and it continues when I leave it (still running in the background):

2021-06-27 10:19:21 	A	api.onesignal.com
2021-06-27 10:17:51 	A	api.onesignal.com
2021-06-27 10:16:20 	A	api.onesignal.com
2021-06-27 10:14:50 	A	api.onesignal.com
2021-06-27 10:13:20 	A	api.onesignal.com
2021-06-27 10:11:05 	A	api.onesignal.com
2021-06-27 10:09:35 	A	api.onesignal.com
2021-06-27 10:08:05 	A	api.onesignal.com
2021-06-27 10:06:35 	A	api.onesignal.com
2021-06-27 10:05:05 	A	api.onesignal.com
2021-06-27 10:03:35 	A	api.onesignal.com
2021-06-27 10:02:05 	A	api.onesignal.com
2021-06-27 10:00:35 	A	api.onesignal.com

**Comment by samwiseg0** [comment]
@nitrox-github please do not post on closed issues. Please use discord support for these types of inquiries. 

Thanks
