### ISSUE TITLE
Wrong Artwork Displayed

### ISSUE THREAD

**Issue by sterod** [Tautulli/Tautulli-Remote#117]
**Describe the bug**
There seems to be a problem with the way the application accesses and displays the artwork of the media being played. For example this morning I added the new Disney movie "Luca" to my PLEX. Initially my PLEX server did not match it correctly and matched it with the wrong movie with the same name from 2019. I  immediately fixed it and matched it to the correct media in the PLEX server, however the remote application is still picking up the incorrect artwork from when it was matched with the wrong movie initially. 

**To Reproduce**
Add media to PLEX.  **PLEX must incorrectly match the media.**  Fix the match in PLEX.

**Expected behavior**
Tautulli should pickup the proper artwork after the media was correctly matched, not the incorrect originally matched media.

**Screenshots**
See subsequent comments.

**Tautulli Info (please complete the following information):**
Pixel 5
Android 11
2.9.0
2.7.3

**Comment by TheMeanCanEHdian** [comment]
Please use the bug report template and verify the data in Tautulli matches what you are seeing in Tautulli remote.

**Comment by sterod** [comment]
![Screenshot_20210618-101442](https://user-images.githubusercontent.com/34377652/122575979-3cf22d80-d01f-11eb-9cb8-d003c68720d0.png)
![Screenshot_20210618-101459](https://user-images.githubusercontent.com/34377652/122576100-58f5cf00-d01f-11eb-9a45-1ed600ef8d1c.png)

**Comment by sterod** [comment]
> Please use the bug report template and verify the data in Tautulli matches what you are seeing in Tautulli Remote.

will do asap.

**Comment by sterod** [comment]
confirming this is a problem with the android app as the tautilli web server shows the correct artwork.

![Capture](https://user-images.githubusercontent.com/34377652/122577827-395fa600-d021-11eb-9286-e78b0fa17e85.JPG)

**Comment by TheMeanCanEHdian** [comment]
Please update your original post to provide the information requested in the bug report template.

**Comment by sterod** [comment]
> Please update your original post to provide the information requested in the bug report template.

Done

**Comment by TheMeanCanEHdian** [comment]
I'm thinking this might be an issue with the Tautulli cache. Can you try the following in a browser and see if it loads the incorrect image?

You will need the following:
- `TAUTULLI_ADDRESS`: ex. 192.168.0.10 or tautulli.domain.com
- `DEVICE_TOKEN`: Found in Tautulli under Settings > Tautulli Remote > _select your device_ > device token or in Tautulli Remote under Settings > _select server_ > device token
- `MEDIA_RATING_KEY`: Found in the URL for the item details in Tautulli

`TAUTULLI_ADDRESS`/api/v2?apikey=`DEVICE_TOKEN`&app=1&cmd=pms_image_proxy&rating_key=`MEDIA_RATING_KEY`

**Comment by sterod** [comment]
Confirmed, the URL loads the artwork for the media before it was correctly matched.

![image](https://user-images.githubusercontent.com/34377652/122597760-db8b8800-d039-11eb-9607-7eeadc51d8ee.png)

**Comment by TheMeanCanEHdian** [comment]
This is a result of cache behavior in Tautulli. Because Tautulli Remote is not asking for an image that is the same size as Tautulli uses the cache for the image Tautulli Remote uses is stale.

There are some things I can do to improve this and I have opened a feature request to track this.

For now if you clear your cache in Tautulli this issue should resolve.

**Comment by TheMeanCanEHdian** [comment]
#119 will be in the next release and use the same poster cache image as Tautulli uses.
