### ISSUE TITLE
Request additional information in the top line showing transfers

### ISSUE THREAD

**Issue by BEisem** [Tautulli/Tautulli-Remote#126]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it seems there is more room in the top line showing the Mbps. Right now it's only using about half the screen real estate, so it would be great if the number of sessions (and maybe number of transcodes) could be added. This information is available in the web version of Tautulli.

**Describe the solution you'd like**
Add number of session and possibly number of transcodes to the top line, in addition to the current transfer speeds.

**Comment by TheMeanCanEHdian** [comment]
An initial implementation of this is available in v3 Alpha 20.
https://github.com/Tautulli/Tautulli-Remote/issues/168
