### ISSUE TITLE
Let the user choose the app language

### ISSUE THREAD

**Issue by CMBoii** [Tautulli/Tautulli-Remote#131]
**Is your feature request related to a problem? Please describe.**

I hate when translations are incompleted/lazily done. However, I'm glad people spent their time on translating the project but unfortunately, I still prefer english over the translation. 

**Describe the solution you'd like**

Having a way to select the language would be way better than letting the app choose the language depending on the system's language. 

This concerns Android.

**Comment by TheMeanCanEHdian** [comment]
I think this is a good call out. I'll get a setting in the next release where this can be configured.

**Comment by TheMeanCanEHdian** [comment]
This has been implemented and will be available in the next release.

**Comment by TheMeanCanEHdian** [comment]
This is live in v2.11.2.
