### ISSUE TITLE
No Splash Screen on iOS when opening app.

### ISSUE THREAD

**Issue by corrupted-josh** [Tautulli/Tautulli-Remote#135]
I’ve noticed recently when launching the iOS app, I get blasted with a totally white screen right before the app loads. Short clip of it in action: https://streamable.com/bgexlq

iOS 14.6
Tautulli Remote v2.11.1 (101)

**Comment by TheMeanCanEHdian** [comment]
A splash screen has been created for iOS (58577b1697a80c459248077cec9a8e48e59abcce) and will be in the next release.

**Comment by TheMeanCanEHdian** [comment]
This is live in v2.11.2.
