### ISSUE TITLE
Add Catalan language

### ISSUE THREAD

**Issue by dtalens** [Tautulli/Tautulli-Remote#136]
**Is your feature request related to a problem? Please describe.**
Please, add support for Catalan lenguaje. I can help to translate.

**Comment by TheMeanCanEHdian** [comment]
Catalan is now available to be translated on [Weblate](https://hosted.weblate.org/projects/tautulli-remote/translations/).

It will be available in app in the next main release.

**Comment by TheMeanCanEHdian** [comment]
This is available in v2.12.1
