### ISSUE TITLE
Add Danish language

### ISSUE THREAD

**Issue by Tntdruid** [Tautulli/Tautulli-Remote#138]
Hello,

Can you add Danish language to the translation site?

**Comment by TheMeanCanEHdian** [comment]
Danish is now available to be translated on [Weblate](https://hosted.weblate.org/projects/tautulli-remote/translations/).

It will be available in app in the next main release.

**Comment by Tntdruid** [comment]
Thanks 👍

**Comment by TheMeanCanEHdian** [comment]
This is available in v2.12.1
