### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by barbuddah** [Tautulli/Tautulli-Remote#147]
### What is your feature request?

Hi, 

I'm interested in helping to translate the app to Russian.

**Comment by TheMeanCanEHdian** [comment]
Hey @barbuddah please use the 'New Language' option when making an issue to request a new language be added!

**Comment by barbuddah** [comment]
> Hey @barbuddah please use the 'New Language' option when making an issue to request a new language be added!

Got it, sorry I'm new to this!
