### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by barbuddah** [Tautulli/Tautulli-Remote#148]
### Have you verified that the language is not already supported?

- [X] I have verified this language is not currently supported

**Comment by TheMeanCanEHdian** [comment]
Russian is now available for translation on Weblate.
https://hosted.weblate.org/projects/tautulli-remote/translations/ru/

It will be available for use in the next app release.

**Comment by TheMeanCanEHdian** [comment]
This is now available in 2.12.2.
