### ISSUE TITLE
Add Czech language

### ISSUE THREAD

**Issue by karelkryda** [Tautulli/Tautulli-Remote#149]
### Have you verified that the language is not already supported?

- [X] I have verified this language is not currently supported

**Comment by TheMeanCanEHdian** [comment]
Czech is now available for translation on Weblate.
https://hosted.weblate.org/projects/tautulli-remote/translations/cs/

It will be available for use in the next app release.

**Comment by TheMeanCanEHdian** [comment]
This is now available in 2.12.2.
