### ISSUE TITLE
Generic blank notifications when Image Type set on v2.12.1

### ISSUE THREAD

**Issue by djnield** [Tautulli/Tautulli-Remote#151]
### Describe the bug

After updating to the newest android mobile remote app (v2.12.1) notifications are appearing generic and blank when `Notification Image Type` is set to `Small Image`

Reverting the type back to `no image` fixes this and notifications with subject and text appear correctly.

### Tautulli Remote Version

v2.12.1

### Tautulli Version

v2.7.5

### Mobile Device

huawei tablet, huawei mate 10 pro

### Mobile OS

Android 10

**Comment by TheMeanCanEHdian** [comment]
This impacts notifications with the small or large image type set.

**Comment by TheMeanCanEHdian** [comment]
This is fixed in v2.12.2.
