### ISSUE TITLE
Add Slovak language

### ISSUE THREAD

**Issue by johny106** [Tautulli/Tautulli-Remote#153]
### Have you verified that the language is not already supported?

- [X] I have verified this language is not currently supported

**Comment by TheMeanCanEHdian** [comment]
This is now available for translation and will be in the next release.

https://hosted.weblate.org/projects/tautulli-remote/translations/sk/

**Comment by TheMeanCanEHdian** [comment]
This is now available on Android and iOS in v2.13.0.
