### ISSUE TITLE
Gray box in Activity details when unknown data is null.

### ISSUE THREAD

**Issue by Mc0023** [Tautulli/Tautulli-Remote#158]
### Describe the bug

Activity UI shows a large gray box when trying to show Live TV activity. It seems to happen only on Live TV streams and doesn't matter if the stream is a direct stream or transcoded or which client is being used for the stream.

![Tautulli iOS live tv activity bug](https://user-images.githubusercontent.com/6260126/135760277-35086691-0c97-4032-a1e3-1b837da19f50.png)

### Steps to Reproduce

1. Start playing any channel on Live TV
2. Open iOS Tautulli
3. Navigate to Activity 
4. Tap on the stream to open the streams information.

### Expected Behavior

Display the stream information just like it does for existing media.

![Tautulli normal behavior ](https://user-images.githubusercontent.com/6260126/135760587-8af01aa9-e766-44bb-ae18-3bb390349ff5.png)

### Tautulli Remote Version

2.13.0

### Tautulli Version

2.7.6

### Mobile Device

iPhone XS Max

### Mobile OS

iOS 15

### Additional Context

Same behavior on iOS 14 as well before I updated my phone.

**Comment by TheMeanCanEHdian** [comment]
There will be a change available in the next release that should stop this behavior. Items that are missing will simply not be displayed.
