### ISSUE TITLE
Date parse issue in history view

### ISSUE THREAD

**Issue by winbatch** [Tautulli/Tautulli-Remote#161]
### Describe the bug

See YYYY
![060B1225-24E2-4730-9935-E01C17125223](https://user-images.githubusercontent.com/2419795/144757383-d4930a13-a78a-4670-831a-7ec9889da495.png)

### Tautulli Remote Version

2.13.2

### Tautulli Version

2.7.7

### Mobile Device

iPhone XR

### Mobile OS

iOS 15

**Comment by TheMeanCanEHdian** [comment]
Please provide your date format from Settings > General in Tautulli.

**Comment by winbatch** [comment]
YYYY-MM-DD and the Time Format field is: YYYY-MM-DD HH:mm:SS
 
(btw, it's a little weird that the input text box for Time Format is so small such that you only see half of it at a time.

![image](https://user-images.githubusercontent.com/2419795/144757581-fd25e27a-9632-4041-9211-ef146f654cc5.png)

Note that the date parsing in Tautulli itself looks proper:
![image](https://user-images.githubusercontent.com/2419795/144757598-1e6a999d-3fd2-4c77-9ecd-4843805c3c9c.png)

**Comment by TheMeanCanEHdian** [comment]
Time Format should not also have the Date Format in it. Use this to see what is supported
![image](https://user-images.githubusercontent.com/16025103/144757635-56319257-e483-4dd7-b1b5-4c34493bee72.png)

**Comment by winbatch** [comment]
oh I see.  though that Click Here link takes you to the same page that includes the date ones....
I now have 'YYYY-MM-DD' for date and 'hh:mm a' for time.  It looks better on remote, though it seems to be ignoring the 'a'?  I see 2021-12-05 12:34:000

**Comment by winbatch** [comment]
Oh, do you have to restart the remote app to see the format change?  (I thought refresh would do it).  Looks like all is good now.  Thanks!
