### ISSUE TITLE
Remember statistics time preference

### ISSUE THREAD

**Issue by SpookyUSAF** [Tautulli/Tautulli-Remote#163]
### What is your feature request?

In the statistics view, there is a time selection which defaults to 30 days. Every time the app is opened, this is 30 days regardless of the last setting used, such as 90 days or custom. I suggest making the last used setting remembered so it doesn’t need to be changed every time. Thanks!

**Comment by JonnyWong16** [comment]
That is already saved in your browser's local storage. Make sure nothing is clearing your local storage when you close the browser.

**Comment by TheMeanCanEHdian** [comment]
This will be available in the next version of the v3 alpha.
