### ISSUE TITLE
[Alpha] - Unable to change language

### ISSUE THREAD

**Issue by CMBoii** [Tautulli/Tautulli-Remote#164]
### Describe the bug

It doesn't matter the language you choose that the app will be always be English. Although, it might be intentional in the alpha release.

Furthermore, the app will choose the system language on the first launch but the app will be in English.

### Steps to Reproduce

Change the language on the settings.

### Tautulli Remote Version

Alpha v1

### Tautulli Version

-

### Mobile Device

Xiaomi Mi 8

### Mobile OS

Android 12

**Comment by TheMeanCanEHdian** [comment]
Translations have been updated and will be available in the next v3 build. Languages can be translated here:
https://hosted.weblate.org/engage/tautulli-remote/
