### ISSUE TITLE
Image notifications for iOS

### ISSUE THREAD

**Issue by foux** [Tautulli/Tautulli-Remote#167]
### What is your feature request?

Today on Android, you can choose to have an image with your notification. It would be great to have that also on iOS. FOr example on this screenshot, the first notification is from `Remote from Tautulli`(the unofficial app), and it has the image of the media. The second is from the official `Tautulli Remote` and haven't got the image.
![IMG_078E3025401D-1](https://user-images.githubusercontent.com/246550/156830225-d25f7dbe-e6ea-4f0d-9c72-971190764f77.jpeg)

### Are there any workarounds?

Use another app

**Comment by TheMeanCanEHdian** [comment]
This will be available in a future update and will require an update to Tautulli as well.

I will comment once this is available and what the required version of Tautulli will be.

**Comment by TheMeanCanEHdian** [comment]
Closing the loop here, this was added back in v3.1.0 which was released in September 2023.
