### ISSUE TITLE
Display Thread ID

### ISSUE THREAD

**Issue by Kazz3r24** [Tautulli/Tautulli-Remote#173]
### Is your feature request related to a problem?

No

### What is your feature request?

I think it would be a great addition to show the Plex thread ID# somewhere in each stream block. This would make troubleshooting issues with specific streams much easier, just enter the thread ID into the console and you'll see everything happening with that specific stream.

### Are there any workarounds?

Only other way of doing this I've seen is to first search logs by username to find the thread ID.

### Additional Context

![image](https://user-images.githubusercontent.com/15070472/168403863-94794c5d-ea09-4f10-aab6-91f32e093c6f.png)

**Comment by TheMeanCanEHdian** [comment]
Is this request supposed to be for Tautulli or Tautulli Remote? 

If it's for Tautulli Remote I am not sure what you are asking for. 
If it's for Tautulli you'll want to resubmit you request here: https://github.com/Tautulli/Tautulli/issues/new/choose
