### ISSUE TITLE
Hostname treated as invalid URL maybe by inURL

### ISSUE THREAD

**Issue by septer012** [Tautulli/Tautulli-Remote#202]
### Describe the bug

Using the QR code scanner, my server registration page was populated.

Primary server populated with: http://tautulli:8181

isURL function must have returned false, but it's pretty valid.  I changed the hostname to an IP address to proceed. 

### Expected Behavior

The form would have accepted http://tautulli:8181 with no error about valid URL 

### Tautulli Remote Version

3.0.2

### Tautulli Version

N/A

### Mobile Device

Samsung S22+

### Mobile OS

Android

### Additional Context

Since two URL are supported, I would assume one would be a local and the other a non-local connections.  I am not familiar yet with this software, but a hostname only is likely what a local connection would use.

**Comment by samwiseg0** [comment]
After discussing this with @TheMeanCanEHdian. This is not something that we would like to support. Currently FQDN/IP is supported and that is what should be use. Assuming the DNS server is going to add the proper suffix is not really the proper way to handle this.

**Comment by septer012** [comment]
@samwiseg0 , @TheMeanCanEHdian: Thanks, I understand,  I should have just used http://tautulli.localdomain:8181/ in my case.
