### ISSUE TITLE
Thumbnails are not showing

### ISSUE THREAD

**Issue by cgbrooking** [Tautulli/Tautulli-Remote#206]
### Describe the bug

There are no media thumbnails showing on the history or library lists, just an !

### Tautulli Remote Version

3

### Tautulli Version

V2.12.4

### Mobile Device

iPhone 11

### Mobile OS

iOS 16.5.1

**Comment by TheMeanCanEHdian** [comment]
Do you use a self-signed cert?

**Comment by cgbrooking** [comment]
This resolved itself, thanks guys.
