### ISSUE TITLE
Swiss german for the lolz?

### ISSUE THREAD

**Issue by Swissschoggi** [Tautulli/Tautulli-Remote#210]
### Have you verified that the language is not already supported?

- [X] I have verified this language is not currently supported

**Comment by TheMeanCanEHdian** [comment]
Hey @Swissschoggi,

Can you provide any resources highlighting the major differences for the written forms of German vs Swiss German?

I'd like to try and avoid a bloated language selection in the app if possible. But I am open to add it if there is good reason and community interest to help translate.

**Comment by Swissschoggi** [comment]
Hello,

There is no official guide to swiss german.
It is written like it is spoken, every swiss german speaking canton will
understand no matter who writes it in which dialect.

But considering this and your wish to not have a bloated language section i
can say it is not necessary to have.

Thank you for reaching out and taking your time anyway and i wish you a
great evening.
