### ISSUE TITLE
Revert back to Primary Connection every launch

### ISSUE THREAD

**Issue by danesanford** [Tautulli/Tautulli-Remote#212]
### Describe the bug

When using the Android version of this app and having both a primary and secondary connection defined in the server settings. When the app is closed and reopened, the app does not default back to the primary connection, it uses the last known setting when it was previously running.

### Steps to Reproduce

1. goto Settings > Servers
2. enter in a valid primary connection (IP address on local network) and valid secondary connection (webaddress accessible externally) 
3. Close app and reload
4. goto Settings > Servers
5. review if primary is being used?
6. disconnect/reconnect to local network to test if app adjusts back to primary connection (when available) 

### Expected Behavior

I would expect the Android app to default back to the primary connection unless the primary connection does not work. Then I would expect the app to attempt the secondary connection.

The app should always default back to the primary connection when initially launched.? 

### Tautulli Remote Version

V3.0.3

### Tautulli Version

V2.12.5

### Mobile Device

Samsung Galaxy s20 Ultra (SM-G988W) 

### Mobile OS

Android 13

### Additional Context

btw, love this app! keep up the great work!

**Comment by TheMeanCanEHdian** [comment]
The app is acting as intended. The app will remember the last working connection address and always try that first before failing over to the other connection address.

If you have a connection address that works inside your network and out, the expectation is you would not require a secondary.

The secondary connection address was designed to be an option for people who cannot use their external connection internally.
