### ISSUE TITLE
Add the ability to customize the home page

### ISSUE THREAD

**Issue by amajed172** [Tautulli/Tautulli-Remote#215]
### What is your feature request?

I only use the remote app for notifications about recently added.
And would like also to have the Recently Added tap as a default page when I start the app.

If maybe you can add an option "Open the last tap"

Thank you so much for Tautulli. Amazing job

**Comment by TheMeanCanEHdian** [comment]
Just to confirm are you asking for:
1. The notification for recently added to take you to the recently added page?
2. The ability to open the app normally and have it take you to the recently added page?

**Comment by amajed172** [comment]
> Just to confirm are you asking for:
> 
> 1. The notification for recently added to take you to the recently added page?
> 2. The ability to open the app normally and have it take you to the recently added page?

I'm asking for number 2.the ability to open the app normally and have it take me to the recently added page.



The reason for that is that I'm using an automated downloader. So I'm checking the recently added page frequently.

**Comment by TheMeanCanEHdian** [comment]
Okay, thank you for confirming.

**Comment by TheMeanCanEHdian** [comment]
This will be available in the next update under Settings > Advanced.

**Comment by TheMeanCanEHdian** [comment]
This is rolling out in v3.2.3.
