### ISSUE TITLE
Myanmar

### ISSUE THREAD

**Issue by sithu015** [Tautulli/Tautulli-Remote#220]
### Have you verified that the language is not already supported?

- [X] I have verified this language is not currently supported

**Comment by TheMeanCanEHdian** [comment]
@sithu015 can you help me confirm which (if any) of these are the most correct word for the language?
- မြန်မာစကား (mramazaga) [mjəmà zəɡá]
- မြန်မာစာ (mranmaza) [mjəmàzà]
- မြန်မာဘာသာ (mranmabhasa) [mjəmà bàðà]

**Comment by sithu015** [comment]
မြန်မာစာ (mranmaza) [mjəmàzà] is most correct word for writing language. 
မြန်မာစကား (mramazaga) [mjəmà zəɡá] is for the spoking language.
So I prefer **မြန်မာစာ (mranmaza) [mjəmàzà].**

**Comment by TheMeanCanEHdian** [comment]
This has been added and will be available in the next update. In the meantime translations can be added [here](https://hosted.weblate.org/projects/tautulli-remote/translations/my/).

Weblate will show the language as Burmese but in the app it will display မြန်မာစာ/Mranmaza.

**Comment by TheMeanCanEHdian** [comment]
This is rolling out in v3.2.3.
