### ISSUE TITLE
Add Bulgarian language

### ISSUE THREAD

**Issue by TopperBG** [Tautulli/Tautulli-Remote#224]
### Have you verified that the language is not already supported?

- [X] I have verified this language is not currently supported

**Comment by TheMeanCanEHdian** [comment]
This will be available in the next update. In the meantime you can update the translations [here](https://hosted.weblate.org/projects/tautulli-remote/translations/bg/).

**Comment by TheMeanCanEHdian** [comment]
This is rolling out in v3.2.3.
