### ISSUE TITLE
Android: Menu closes automatically the first time it's opened

### ISSUE THREAD

**Issue by bigdwg71** [Tautulli/Tautulli-Remote#226]
### Describe the bug

S20+
Android 13
OneUI 5.1

Everytime I open the Tautulli app for the first time and try to open the 3 bar menu, it starts to open and then immediately closes. It works fine after that. It also works after minimizing and reopening. It only auto closes the first time it's opened on fresh start.

### Steps to Reproduce

1. Force stop Tautulli
2. Open Tautulli
3. Open menu by pressing 3 bar button

### Expected Behavior

The menu should stay open the first time I open it.

### Tautulli Remote Version

3.22

### Tautulli Version

2.13.2

### Mobile Device

S20+

### Mobile OS

Android 13

**Comment by TheMeanCanEHdian** [comment]
I am unable to reproduce this. Can you share a screenshot of the about dialog to verify your app version? Can you provide a video showing the issue and you reproducing it?

**Comment by bigdwg71** [comment]
@TheMeanCanEHdian screenshot attached. I'll send you a PM with a link to the video. Thanks for looking into this!


![Screenshot_20231106_114613](https://github.com/Tautulli/Tautulli-Remote/assets/26982284/22083029-6d6d-4875-bfbb-cd944ae2269b)

**Comment by bigdwg71** [comment]
@TheMeanCanEHdian any thoughts?

**Comment by TheMeanCanEHdian** [comment]
I have been unable to reproduce this at all over the last month. I think I'm going to need the system logs from your device to try and troubleshoot any further. [This guide runs over how to get Logcat logs](https://support.citrix.com/article/CTX232375/how-to-install-and-collect-adb-logs-on-android-device). You should be good to run the logs, trigger the  issue, and then stop the log export.

**Comment by bigdwg71** [comment]
[logcat-trim.zip](https://github.com/Tautulli/Tautulli-Remote/files/13705115/logcat-trim.zip)

@TheMeanCanEHdian I have a attached a logcat file. It appeared to include logs from many minutes before my test as well so I trimmed it down a bit as it was also 80+ MB.

I opened Tautulli at 9:40a and the log timestamp appears to be 12-18 09:40:11.858. I only attempted to open the menu once which immediately closed. I did not open it a second time. Although I can recreate this test easy enough. Let me know. Thanks!

**Comment by TheMeanCanEHdian** [comment]
There was nothing obvious in the logs. I'll add some logging for this in the next build so we can try to chase down the cause.

**Comment by TheMeanCanEHdian** [comment]
@bigdwg71 can you confirm if this happens when you swipe open the menu instead of using the button in the top left?

**Comment by TheMeanCanEHdian** [comment]
Great, thank you.

**Comment by TheMeanCanEHdian** [comment]
v3.2.3 is rolling out now, once you update I'll have you reproduce and provide those logcat logs again.

**Comment by bigdwg71** [comment]
@TheMeanCanEHdian logs attached. Sorry for the delay!

[logcat.zip](https://github.com/Tautulli/Tautulli-Remote/files/14281552/logcat.zip)

**Comment by TheMeanCanEHdian** [comment]
Well I'm not seeing any obvious errors in the logs.

Does the menu auto close if the first time you press the menu button is on a page besides activity? You can most easily test this by changing the home page for the app under settings.

**Comment by bigdwg71** [comment]
@TheMeanCanEHdian I just tested with both History and Recently Added as the home page with the same result. Never happens with the swipe to open. Also, I recently upgraded from the S20+ to the S24 Ultra and the issue persisted. Just adding that additional data point.

**Comment by nomad64** [comment]
I have also been experiencing this issue. It started in my Pixel 6 Pro and continued occurring on my Pixel 8 Pro. When moving phones, I moved the data as well. 

 When I try to open the menu via the menu button after opening the app, it immediately closes. Subsequent menu opens work normally. Opening the menu by swiping works normally every time.

Android version: 14
Tautulli App version: 3.2.3

Note: If I clear all app data and re-register the tautulli server, the menu opens normally during the initial use. The issue reoccurs once I close the app (via the back button) and open it again.

**Comment by TheMeanCanEHdian** [comment]
I'm working on adding the ability to do over the air patches to the app to help with troubleshooting this issue. In the meantime, @bigdwg71 or @nomad64, can you try the following and tell me the behavior?
1. Clear the app data
2. Quit the Wizard (do not add servers)
3. 3. Without servers configured can you reproduce the drawer issue?

**Comment by nomad64** [comment]
@TheMeanCanEHdian I performed the requested steps. After closing the wizard, I opened the drawer and it opened correctly; the issue did not occur. I then backed out, opened the app, and tried the drawer again. This time the issue did occur; the drawer closed immediately.

Hope this helps!

**Comment by nomad64** [comment]
@TheMeanCanEHdian Just a heads up that today I noticed this bug is no longer happening for me. I have repeated the same test I have been doing and the menu opened normally every time.

@bigdwg71 Has the issue also been resolved for you?

**Comment by bigdwg71** [comment]
@TheMeanCanEHdian @nomad64 I can still reproduce this issue on fresh start.

**Comment by kafkaguru** [comment]
I just wanted to comment that this has been happening for me for a while as well.

Currently on the Pixel Fold
Happens on Android 14 and 15

Edit: I followed the steps above to clear app data, not add a server, then test. The side bar opens the first time.

After force closing and reopening, it quickly closes again

**Comment by bigdwg71** [comment]
@TheMeanCanEHdian I realized about a week ago that this issue is no longer happening to me. Not sure if there was an update that specifically addressed this or not, but I can no longer reproduce the issue.

@nomad64 @Brianbrifri can you confirm the same?

**Comment by nomad64** [comment]
@bigdwg71 I have been using the app since September without this reoccurring.

**Comment by kafkaguru** [comment]
> @TheMeanCanEHdian I realized about a week ago that this issue is no longer happening to me. Not sure if there was an update that specifically addressed this or not, but I can no longer reproduce the issue.
> 
> @nomad64 @Brianbrifri can you confirm the same?

It seems fixed for me now!

**Comment by bigdwg71** [comment]
Seems to have been resolved.
