### ISSUE TITLE
Plex Home Family Members not reporting Live TV in Graphs 

### ISSUE THREAD

**Issue by Dragonwyntir** [Tautulli/Tautulli-Remote#228]
### Describe the bug

My brother is part of my Plex Home, and watches Live TV. His Live TV usage is not reported at all in the Graphs, even though it is reported in the History. 

### Tautulli Remote Version

3.2.2

### Tautulli Version

2.13. 4

### Mobile Device

Samsung Galaxy Fold 5

### Mobile OS

Android 14

**Comment by TheMeanCanEHdian** [comment]
Are the graphs the same as those in the Tautulli Web UI? Can you provide screenshots showing the difference if not?

**Comment by Dragonwyntir** [comment]
Hi, I just checked and it seems they are missing there as well (sorry I never go over there because I love the mobile app so much).

**Comment by TheMeanCanEHdian** [comment]
No worries, I'm not sure what the expected behavior is. You'll want to raise this question on the Tautulli repo (if there isn't an existing issue about it).
