### ISSUE TITLE
Max WAN speed tracking and graphing

### ISSUE THREAD

**Issue by klatch29** [Tautulli/Tautulli-Remote#230]
### What is your feature request?

I like the new concurrent stream count graph and was wondering if it is possible to track and graph the daily max WAN speed, to help track internet usage demands, to help determine when I should be upgrading my internet package.

**Comment by TheMeanCanEHdian** [comment]
Hey @klatch29,

Tautulli Remote requires Tautulli to have API endpoints for the data it displays. You'll want to make any of these sorts of requests on the Tautulli repo. Make sure to check if there are existing feature requests for what you are looking for, so you don't make a duplicate.
