### ISSUE TITLE
Android app says an update is available 

### ISSUE THREAD

**Issue by rhythmrice** [Tautulli/Tautulli-Remote#250]
### Describe the bug

The Android app says update is available but when you click "update" it opens the Google Play store and there is no update, I can only uninstall or open the app. 

I believe the last update was the one that let you save filters in the history, and i can do that, so I should be completely up to date. When i click "about" it says im on 3.3.0

I cant get it to stop saying there is an update available 

### Steps to Reproduce

Open the app, the 3 horizontal lines icon on the top left has a yellow dot on it.

Go to settings and there is a big yellow banner that says an update is available 

Clicking "update" opens the google play store but there is no update available 

### Expected Behavior

It should not say there is an update 

Or when I click "update" and it goes to the google play store, there should be an update available to download 

### Tautulli Remote Version

v3.3.0

### Tautulli Version

v2.14.5

### Mobile Device

Galaxy S24 Ultra

### Mobile OS

Android 14 One UI 6.1

**Comment by TheMeanCanEHdian** [comment]
Looks like this is an issue with the package used for this feature not working correctly. Going to disable it until it is fixed.

**Comment by TheMeanCanEHdian** [comment]
v3.3.1 has been published to the app store and resolves this for now.
