### ISSUE TITLE
Sort on History Frag

### ISSUE THREAD

**Issue by JamminR** [Tautulli/Tautulli-Remote#36]
When using PlexPy through the web interface, the ability to sort users by different columns is nice (last used, reverse alphabetical, IP, total plays, etc.)
The ability to sort Users (and even other screens/History,etc) in PlexPy Remote would be a great addition.

**Comment by wcomartin** [comment]
sorry for hijacking your issue but im trying to organize and create smaller issues

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
