### ISSUE TITLE
Update media item profile page to better display info next to poster

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [Tautulli/Tautulli-Remote#52]

**Comment by Wreave** [comment]
![example.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59678cc83a9759001a2cc6c0/125516c66e82c728ace21e0d46ed8c9b2e928faccda5fd53b652fa912a5265296b51fa7d27dde17bee117e58585f46ac415a5f11f9fa8878a2a42062c80d55b98e30063e937f03a6aa8318b500bf218e4984b1b8824dc5ea3e37aa.png)

**Comment by JonnyWong16** [comment]
Unify design across app and web? 

Headers are smaller font, grey, all caps. 
Values are regular font, white, not caps.
