### ISSUE TITLE
Automatic popping up keyboard in History

### ISSUE THREAD

**Issue by romanar** [Tautulli/Tautulli-Remote#55]
I'm not sure if this is a feature or bug. 
However, when I click on History Android Virtual Keyboard poops up automatically.

**Comment by TATUMTOT** [comment]
Ya i have the same issue.

**Comment by wcomartin** [comment]
It's a bug, it'll be fixed in next release

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
