### ISSUE TITLE
Notifications not being shown after update to Android 8.1

### ISSUE THREAD

**Issue by rigrassm** [Tautulli/Tautulli-Remote#57]
Updated to Android 8.1 Oreo(Lineage OS 15.1) yesterday and noticed I wasn't getting notifications. I have since tried removing and registering the device again but still am unable to get notifications. 

Sending test notifications from the web interface shows they are being sent and the logs show this as well but the notification is never displayed on the phone. 

Tested with pushbullet and those came through without any issues.

**Comment by Arcanemagus** [comment]
Did you try clearing data for the app itself?

**Comment by rigrassm** [comment]
Funny you should ask that, I just did that and it started working after clearing all the data and reconfiguring. Just came here to update the issue when I noticed your comment.

As a Sysadmin by trade I should have thought of this 5 min into troubleshooting lol.

Sorry for the hassle, closing out the issue now.
