### ISSUE TITLE
Record Notification History

### ISSUE THREAD

**Issue by rigrassm** [Tautulli/Tautulli-Remote#58]
It's awesome to get the Tautulli notifications on my phone, the only thing missing is the ability to see a list of prior notifications. This would useful for when there are a larger number of notifications coming in a short period of time so you can go back and see if anything was missed.

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
