### ISSUE TITLE
Support SSL client certificates

### ISSUE THREAD

**Issue by JohnKis** [Tautulli/Tautulli-Remote#60]
Hi there,

Is there any chance for adding support for SSL client certificates?

On my server, all the remotely accessible sites are protected with ssl client certs. The certificate is installed on my iPhone and I can access the web UI in safari, however not through the app.

If the app could use the certificates installed to iOS, that’d be great but if it’s not possible, having a way to provide the cert in the app directly would be useful as well.

**Comment by JohnKis** [comment]
I'm sorry, only just realised that this is the repo of the Android app. I'll open the same issue in the iPhone repo as well (if I can find it)

**Comment by TheMeanCanEHdian** [comment]
Remote for Tautulli is a 3rd Party app not managed by us.

Currently, there are no plans to support certs in the app. You should be bypassing any auth requirements for the /api path at this time.
