### ISSUE TITLE
Unsupported SSL Version being used!

### ISSUE THREAD

**Issue by Kopertje** [Tautulli/Tautulli-Remote#62]
Hi there! Im looking for some support about getting Tautulli to work on SSL. I have the python modules installed and i got a valid cert installed. When i goto the HTTPS link in Chrome i get an invalid SSL version error from Chrome. How can i change the SSL version?

Error i am getting:
This site can’t provide a secure connection
<domain> uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Could anyone help me with this? Are there more people with the same issue?

**Comment by JonnyWong16** [comment]
GitHub Issues are for bug reports, and not for support. Please use our [Discord server](https://tautulli.com/discord).
