### ISSUE TITLE
Translation French 

### ISSUE THREAD

**Issue by FayzB** [Tautulli/Tautulli-Remote#65]
Hello
Here is a French translation of the application.
It lacks parts that must be in smali ect files ... to see if possibility to integrate them in strings.xml or arrays.xml

[values-fr.zip](https://github.com/Tautulli/Tautulli-Remote/files/2373000/values-fr.zip)

**Comment by FayzB** [comment]
https://github.com/FayzB/Translation-APKs/tree/master/PlexPy/values-fr

**Comment by pmspr4100** [comment]
Fix transalation french 

https://github.com/pmspr4100/XML-APK-FRENCH/tree/master/PlexPy/values-fr

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
