### ISSUE TITLE
Notifications cannot be read fully because they are non-expandable

### ISSUE THREAD

**Issue by crafty35a** [Tautulli/Tautulli-Remote#66]
The notification text is often far too long to fit in a single line, but the notifications are not expandable so there is no way to fully view the text. Often all I can see is something like "UserName (Playstation) has watched A..."

Could you change it to use one of the expandable notification types?

https://developer.android.com/training/notify-user/expanded

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
