### ISSUE TITLE
App removed from Play store

### ISSUE THREAD

**Issue by modem7** [Tautulli/Tautulli-Remote#67]
Android app has been removed from play store.

Unsure if intentional or a bug.

"We're sorry, the requested URL was not found on this server."

**Comment by modem7** [comment]
I see from https://www.reddit.com/r/Tautulli/comments/abn7bk/tautulli_remote_not_available_on_play_store/ that it's been taken down for violations and appeal requested.

**Comment by Comfubar** [comment]
Is their any way to get the APK I just found out about this and wiped my phone unable to get the app back

**Comment by Arcanemagus** [comment]
It's available for download here:
<https://discordapp.com/channels/183396325142822912/310655997272391692/533021464140447745>

**Comment by Comfubar** [comment]
Awesome Thank you :)

**Comment by dagayveggi** [comment]
Any plans to get it back in the store? I can't install an app on my work phone, only apps from the play store ☹️
