### ISSUE TITLE
You server is not reachable! Could not connect to Tautulli

### ISSUE THREAD

**Issue by ng4ever** [Tautulli/Tautulli-Remote#68]
I keep getting this error but my server is connected. 

![img_0002](https://user-images.githubusercontent.com/17295139/52535582-bc67e780-2d15-11e9-83ef-f3a5d4357c70.PNG)

**Comment by TheMeanCanEHdian** [comment]
This is an unofficial app that we do not provide support for. You'll need to contact the dev.
