### ISSUE TITLE
Manual connection IP1 / IP2

### ISSUE THREAD

**Issue by FayzB** [Tautulli/Tautulli-Remote#69]
Hello possible to have as on the application Plex Android

A manual connection option
IP address 1: IP Local
Port 1:

IP address 2: IP External
port2:

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
