### ISSUE TITLE
Disable tracking and analytics to FireBase

### ISSUE THREAD

**Issue by SvenssonWeb** [Tautulli/Tautulli-Remote#70]
If using this application in a network protected with Pi-Hole or similar tracking prevention, device registration fails because a lookup to app-measurement.com.

This originates from the use of Firebase, and prevents the registration to complete for some reason.

If possible, consider disabling tracking, based on the official documentation in the link below:
https://firebase.google.com/support/guides/disable-analytics

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
