### ISSUE TITLE
Arrow icon not displayed for subtitles transcode in Activity details

### ISSUE THREAD

**Issue by thunder2k** [Tautulli/Tautulli-Remote#73]
As per title.
Check attached screenshot
![Screenshot_20190730-213759_2](https://user-images.githubusercontent.com/43518960/62216601-f353b780-b3a0-11e9-94a2-db992ae6c74c.jpg)

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
