### ISSUE TITLE
TLS 3: HTTPS enabled you are not using port 80

### ISSUE THREAD

**Issue by hwwilliams** [Tautulli/Tautulli-Remote#76]
I noticed that if I attempt to serve the tautulli api over TLS 3 I get the following error, "HTTPS is enabled but port is 80", which isn't really accurate about what the issue is.

Switching back to TLS 2 and everything works fine.

I'm just mentioning this so the error message can be updated on the app.

**Comment by JonnyWong16** [comment]
But report template not filled out.

**Comment by hwwilliams** [comment]
I'm not sure why but I can't see this comment on the github issue anymore,
I also can't find a bug report template.

If you could point me in the right direction I'll update the issue.

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
