### ISSUE TITLE
Request for packaging in F-Droid

### ISSUE THREAD

**Issue by m-boyd** [Tautulli/Tautulli-Remote#77]
WIth some modifications, this app could be added to F-Droid's mainline repository to expand its audience beyond just the Google Play Store.

[https://gitlab.com/fdroid/rfp](https://gitlab.com/fdroid/rfp)

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
