### ISSUE TITLE
Update Tautulli Panel: Minor spelling typo

### ISSUE THREAD

**Issue by DevMan01** [Tautulli/Tautulli-Remote#79]
Found a minor spelling typo. "beeing" should be "being" in the sentence:

> "Tautulli is beeing updated."
![IMG_4044](https://user-images.githubusercontent.com/24305516/87239365-92639a80-c3cb-11ea-9fa5-c9480313de63.PNG)

**Comment by JonnyWong16** [comment]
That's not our app. The iOS app is not created by us.
