### ISSUE TITLE
Can't register new device using a self-signed certificate

### ISSUE THREAD

**Issue by zeeter82** [Tautulli/Tautulli-Remote#82]
I've been using the older Tautulli Remote for a couple years now with no issues.  I just updated to new preview app from Play store and I tried adding my server and I keep getting "Failed to establish TLS/SSL connection".  I tried using the QR code and manually entering the info.  Fails both ways.

Please advise.

**Comment by joshbgosh10592** [comment]
Not sure if mine is related, but I have a reverse proxy, secured with ask and when I scan the QR code, the webUI shows registered successfully, but the app shows "Unexpected Error" with no other information.

**Comment by zeeter82** [comment]
I just updated app to 2.3.2 and it still won't let me add device....same TLS/SSL error.

![Screenshot_20210308-113152](https://user-images.githubusercontent.com/17049920/110350779-0f4e1f00-8002-11eb-8075-7707c1877eda.png)

**Comment by JonnyWong16** [comment]
Are you using a self-signed certificate?

![image](https://user-images.githubusercontent.com/9099342/110350923-13ba0e00-7fe9-11eb-9f69-741bc24b758e.png)

**Comment by zeeter82** [comment]
Yep and everything with accessing the web interface via HTTPS seems to work fine.

**Comment by zeeter82** [comment]
The older remote app version didn't have any issues adding my HTTPS server to my Pixel 5.

**Comment by joshbgosh10592** [comment]
@JonnyWong16 Not OP, but similar issue (I believe). 
I have both of those selected, but not "Enable HTTP Proxy" even though I have my environment set up like that. I use LetsEncrypt as my cert provider, and the cert is imported into my reverse proxy.
If you think mine is different, I'll create a separate issue.

**Comment by zeeter82** [comment]
I've tried to get LetsEncrypt working with my Tautulli environment since it's obviously much better than self-signed, but I never could get it working.  Your issue might be different.

**Comment by JonnyWong16** [comment]
@joshbgosh10592 Your issue is unrelated. `ServerVersionException` indicates that your Tautulli version is too old. The new app requires Tautulli v2.6.6 or newer.

**Comment by zeeter82** [comment]
Here is remote app log:

![Screenshot_20210308-114417](https://user-images.githubusercontent.com/17049920/110352396-e2027080-8003-11eb-8cf3-627f1536275f.png)

**Comment by TheMeanCanEHdian** [comment]
@zeeter82 using the cert settings in Tautulli is not something I had tested. Can you make a bug report with the template and reference this issue in it when making it? We can then close this out and work off that as needed

**Comment by zeeter82** [comment]
Opened new issue using template.  Closing this issue.
