### ISSUE TITLE
Can't register new device using a self-signed certificate

### ISSUE THREAD

**Issue by zeeter82** [Tautulli/Tautulli-Remote#83]
**Describe the bug**
Can't register new device using a self-signed certificate.  I'm trying to add my self-signed HTTPS enabled Tautulli server to my Pixel 5 device.

**To Reproduce**
1. Adding new server in the app produces the error "Failed to establish TLS/SSL connection".  Both the QR code and manual input methods produce same error.

**Expected behavior**
My server will be successfully added to mobile device running Tautulli Remote app.

**Screenshots**

![Screenshot_20210308-113152](https://user-images.githubusercontent.com/17049920/110354760-84235800-8006-11eb-9b20-a7d05aa34857.png)

![Screenshot_20210308-114417](https://user-images.githubusercontent.com/17049920/110354774-88e80c00-8006-11eb-9f5e-86331166f057.png)

**Smartphone (please complete the following information):**
 - Device:  Pixel 5
 - OS:  11
 - Server Version 2.6.7
 - App Version 2.3.2

**Comment by TheMeanCanEHdian** [comment]
Thanks for getting this submitted.

**Comment by pjumper07** [comment]
Hey, FYI I also get this with a public cert I am using Rapid SSL and get the exact same as above, my app just refuses to connect also manual or QR code.

**Comment by samwiseg0** [comment]
Rapid SSL may not be trusted by your android phone. https://stackoverflow.com/questions/7203857/rapidssl-certificate-not-trusted-on-android-tablet

**Comment by pjumper07** [comment]
> Rapid SSL may not be trusted by your android device. https://stackoverflow.com/questions/7203857/rapidssl-certificate-not-trusted-on-android-tablet

Thanks for the link but that article is from 2013 an this has been working for over a year my phone hasnt changed only the app for Tautulli with the extact same error with self signed so seems to be more a app and SSL/TLS issue.

**Comment by samwiseg0** [comment]
@pjumper07 If that is the case I suggest you open a new issue as it is not related to this one. Please fill out the template and provide your logs.

**Comment by JonnyWong16** [comment]
The old Tautulli Remote app blindly accepted all certificates so you would not have known if your certificate had issues.

**Comment by pjumper07** [comment]
@samwiseg0 Thats incorrect the issue is exactly the same I was merely adding that its not just self-signed certs this is happening its also public certs as well. Apart from the the issue and errors are identical, so not a separate issue.

**Comment by pjumper07** [comment]
@JonnyWong16  Thanks I agree its possible it was just accepting the certificate but the browser versions work perfectly fine too on both Android, Windows and iOS. An I am not the only one that has commented this see there is already 2 issues just worded differently, I was just trying to add more info and not just think its only self-signed that was the issue.

**Comment by samwiseg0** [comment]
> this is happening its also public certs as well. Apart from the the issue and errors are identical, so not a separate issue.

Exactly. You just stated how this is a different issue. The errors may be the same but the problem is different. Trusted certificates should not give this error. Please open a separate issue.

**Comment by samwiseg0** [comment]
@pjumper07 Please follow https://github.com/Tautulli/Tautulli-Remote/issues/89 as it pertains more to your problem specifically. 

Thanks

**Comment by TheMeanCanEHdian** [comment]
@zeeter82 Tautulli Remote v2.4.0 is currently under review (likely to be available within a few hours). This adds the ability to trust self-signed certs or certs the app was unable to authenticate.

Can you give this a try and report back if it fixes your issue?

**Comment by zeeter82** [comment]
Absolutely!  I'll try it tomorrow morning.

Thanks!

**Comment by zeeter82** [comment]
Updated app and this fixed my issue.  I got the warning popup about my self-signed cert and clicked on trust.  Seems to be working fine.

Thanks!
