### ISSUE TITLE
New Tautulli Remote doesn't want to register on phone

### ISSUE THREAD

**Issue by Rawh** [Tautulli/Tautulli-Remote#84]
**Describe the bug**
Cannot register the beta version of the android app

**To Reproduce**

1. Login to my own website version of Tautulli.
2. Click on the "Help & Info" tab of the menu to the left, click on the changelog-hyperlink next to version and belows info shows:
![image](https://user-images.githubusercontent.com/10486655/110360554-265f3200-803f-11eb-8dd9-59a2a8d095f1.png)
2. Click on the "Tautulli Remote Android App beta" tab of the menu, click on the gearwheel (bottom right) and select "add new device". 
3. Scan the QR code for the new tautulli-remote app and an error shows
``` 
{LoggingDataSourceImpl} {info} {Settings: Mask Sensitive Info enabled} {LogLevel.INFO} {08 March 2021 05:39:05 PM} 
{LoggingDataSourceImpl} {info} {OneSignal: Privacy consent accepted} {LogLevel.INFO} {08 March 2021 05:39:26 PM} 
{LoggingDataSourceImpl} {error} {RegisterDevice: Failed to register device [ServerVersionFailure]} {LogLevel.ERROR} {08 March 2021 05:43:59 PM} 
{LoggingDataSourceImpl} {error} {RegisterDevice: Failed to register device [ServerVersionFailure]} {LogLevel.ERROR} {08 March 2021 06:45:37 PM} 
``` 
The error in the screen says "update to 2.6.6 or greater". I have version 2.6.7 running, as shown in the picture. What am I doing wrong?

**Expected behavior**
App gets installed, stuff works

**Screenshots**
See text above

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T (A5010)
 - OS: Android 10
 - App Version: Tautulli Remote 2.3.2 (the new beta one from the announcement)

**Additional context**
Other app v1.4.200 still works (-:

**Comment by S1M0N** [comment]
Not sure this is the exact same issue, but it does seem to be so adding in here, if this is different let me know and I can open a new issue. 

I am having similar issues with the beta app (Tautulli Remote v2.3.2) as well, while on Tautulli v2.6.8.   

Installed app using [link in web interface](https://play.google.com/store/apps/details?id=com.tautulli.tautulli_remote).   

After doing this (and verifying install on mobile device) I selected the `Register a new device` option in the web interface, then scanned the QR Code from the mobile app, after this I received a `Failed to establish TLS/SSL connection. Check your Connection Address for errors.` message (see below for screen shots). I then manually entered server URL and Device Token, but received same error.  

I can verify that the server has a valid SSL Cert and is reachable, however it only supports TLS v1.3 and denies connections of any lower protocol. :
<img src="https://user-images.githubusercontent.com/727018/110395418-13972e00-803c-11eb-9ebe-917f21a04960.png"  width="500" height="229">  
<img src="https://user-images.githubusercontent.com/727018/110395750-b6e84300-803c-11eb-9e76-05baad04e4c8.png"  width="500" height="119">

#### App Error Message
<img src="https://user-images.githubusercontent.com/727018/110394580-a9ca5480-803a-11eb-90c6-504af077ea70.png"  width="500" height="365">

#### App Logs:  
<img src="https://user-images.githubusercontent.com/727018/110395186-b13e2d80-803b-11eb-9c99-af894a56be59.png"  width="500" height="1010">

**Comment by samwiseg0** [comment]
@S1M0N What root CA are you using?

**Comment by S1M0N** [comment]
> @S1M0N What root CA are you using?

Issuer Let’s Encrypt R3 - https://letsencrypt.org/certificates/

**Comment by samwiseg0** [comment]
@S1M0N I am going to transfer your comment to a new issue as it is different since its a valid CA.

**Comment by S1M0N** [comment]
@samwiseg0 Sounds good!

**Comment by samwiseg0** [comment]
@S1M0N Lets continue the discussion on https://github.com/Tautulli/Tautulli-Remote/issues/89

Thanks

**Comment by TheMeanCanEHdian** [comment]
@Rawh just wanted to check if Tautulli 2.6.8 fixed this for you?

**Comment by Rawh** [comment]
Hi. Sorry wasn't at home, couldn't touch the docker container which I have running for tautulli to update. Seems the image I run from linuxserver.io has updated itself already in the background and the server is now running version 2.6.8

I have also noticed your app received a couple of updates since my bug report (I'm now running 2.4.1). Somewhere along that line the bug got fixed. I have just successfully added my server to the client-app. Thanks for the quick response!

You can close the bug report if you want to.
