### ISSUE TITLE
Landscape Operation

### ISSUE THREAD

**Issue by sterod** [Tautulli/Tautulli-Remote#85]
Hello I frequently use this application with a tablet that I have permanently fixed in a landscape orientation. It would be nice if the application could be given a dedicated landscape mode so that I don't have to twist my head every time I want to use it as it appears to be locked in portrait mode only.

**Comment by TheMeanCanEHdian** [comment]
Please use the template for feature requests.

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
