### ISSUE TITLE
Landscape Mode

### ISSUE THREAD

**Issue by sterod** [Tautulli/Tautulli-Remote#87]
**Is your feature request related to a problem? Please describe.**
Yes, the app appears to force portrait mode only and does not rotate to landscape when the device is rotated.

**Describe the solution you'd like**
I would like the application to have a landscape mode to follow the rotation of the device.

**Describe alternatives you've considered**
None, my device is in a permanent landscape mode.

**Additional context**
None.

**Comment by TheMeanCanEHdian** [comment]
This is something I'd like to get to eventually to also help with tablet support.

At the moment it is a lower priority.

**Comment by sterod** [comment]
Thank You, I've been using this app for years and when the new version was offered today I sent a donation to the author.

**Comment by TheMeanCanEHdian** [comment]
Landscape mode is currently available in the Alpha app.

If you are on Android feel free to [install the alpha](https://github.com/Tautulli/Tautulli-Remote/issues/168) to test this. Otherwise, it will be available on both platforms at a later date.
