### ISSUE TITLE
History Tab

### ISSUE THREAD

**Issue by mattm3** [Tautulli/Tautulli-Remote#88]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem but the history tab on the old app showed details when you tapped and held down, the details were started, stopped, paused, duration, IP address and player.

**Describe the solution you'd like**
It would be great to have something like the above added to the new app.

**Describe alternatives you've considered**
There isn't any alternatives currently.

**Additional context**
N/A

**Comment by TheMeanCanEHdian** [comment]
This will be added in the next release. A tap of the history item will bring up a bottom sheet with all the details like on the activity page.

**Comment by TheMeanCanEHdian** [comment]
This is now live in v2.6.0+.
