### ISSUE TITLE
Public root CA not trusted and giving a TLS error using TLS 1.3

### ISSUE THREAD

**Issue by samwiseg0** [Tautulli/Tautulli-Remote#89]
**Describe the bug**
Not sure this is the exact same issue, but it does seem to be so adding in here, if this is different let me know and I can open a new issue. *Edit:* Just noticed #83 seems to maybe be more appropriate, I didn't initially select it as I'm not using a self-signed cert. I'll leave this here for now, let me know if you want me to move it.

I am having similar issues with the beta app (Tautulli Remote v2.3.2) as well, while on Tautulli v2.6.8.   

Installed app using [link in web interface](https://play.google.com/store/apps/details?id=com.tautulli.tautulli_remote).   

After doing this (and verifying install on mobile device) I selected the  option in the web interface, then scanned the QR Code from the mobile app, after this I received a  message (see below for screen shots). I then manually entered server URL and Device Token, but received same error.  

I can verify that the server has a valid SSL Cert and is reachable, however it only supports TLS v1.3 and denies connections of any lower protocol. :
<img src="https://user-images.githubusercontent.com/727018/110395418-13972e00-803c-11eb-9ebe-917f21a04960.png"  width="500" height="229">  
<img src="https://user-images.githubusercontent.com/727018/110395750-b6e84300-803c-11eb-9e76-05baad04e4c8.png"  width="500" height="119">

**To Reproduce**
1. Attempt to connect to Tautulli using Let’s Encrypt R3 - letsencrypt.org/certificates

**Expected behavior**
The app connects without error when using a public CA

**Smartphone (please complete the following information):**
 - App Version **Tautulli Remote v2.3.2**

**Additional context**

#### App Error Message
<img src="https://user-images.githubusercontent.com/727018/110394580-a9ca5480-803a-11eb-90c6-504af077ea70.png"  width="500" height="365">

#### App Logs:  
<img src="https://user-images.githubusercontent.com/727018/110395186-b13e2d80-803b-11eb-9c99-af894a56be59.png"  width="500" height="1010">

_Originally posted by @S1M0N in https://github.com/Tautulli/Tautulli-Remote/issues/84#issuecomment-793172243_

**Comment by S1M0N** [comment]
@samwiseg0 Let me know what you need from me, happy to help!

**Comment by TheMeanCanEHdian** [comment]
@S1M0N Tautulli Remote v2.4.0 is currently under review (likely to be available within a few hours). This adds the ability to trust self-signed certs or certs the app was unable to authenticate.

Can you give this a try and report back if it fixes your issue?

**Comment by Eliesemoule** [comment]
Hello,

I have the same bug with 2.3.8 version and always after update to 2.4.0. I use Let's Encrypt certificate and TLS 1.3. Tautulli version on server is 2.6.8.

I can do some test, if you want :-)

**Comment by TheMeanCanEHdian** [comment]
@Eliesemoule are you saying you have the same issue even on 2.4.0?

**Comment by S1M0N** [comment]
Hey @TheMeanCanEHdian, I just verified mobile app version as 2.4.0 and attempted device registration again, unfortunately I ran into the same issue as originally reported. I even cleared all stored app data and app cache, as well as fully uninstalling and reinstalling, unfortunately the issue persists. 

<img src="https://user-images.githubusercontent.com/727018/110478680-95c23980-80b2-11eb-8753-4dd3812e4714.png"  width="500" height="365">

**Comment by Eliesemoule** [comment]
@TheMeanCanEHdian  Yes I confirme the same issue with Tautulli Remote 2.4.0

**Comment by TheMeanCanEHdian** [comment]
This appears to be an issue where the stable channel for Dart is using a version of [BoringSSL that does not have TLS v1.3 enabled](https://github.com/dart-lang/sdk/issues/41061#issuecomment-781276323) by default.

They [pushed an update to the dev channel](https://github.com/dart-lang/sdk/commit/c1677553d1ef529ecdbc1caba877ae2ab5e35bd4) a bit ago so we just need to wait for that to roll into stable.

**Comment by Eliesemoule** [comment]
I confirm I can register my Plex server after activate TLS v1.2. Thanks for your update :-)

**Comment by TheMeanCanEHdian** [comment]
@S1M0N I believe this fix is now in the stable Dart build. Would you be willing to alpha test and confirm?

**Comment by TheMeanCanEHdian** [comment]
Should be fixed in version 2.10.0.

**Comment by Erwan-loot** [comment]
i've dl the 2.10.0 it works well done
