### ISSUE TITLE
Double Tap To Exit

### ISSUE THREAD

**Issue by Rossaluss** [Tautulli/Tautulli-Remote#90]
**Is your feature request related to a problem? Please describe.**
In the old app, if you were in a sub-menu, or an alternate screen, if you pressed 'back', you were returned to the the activity screen, and you needed to press back twice on that screen to exit the app, to prevent accidental closure.

**Describe the solution you'd like**
I'd like this functionality to be replicated to the new app, as using gesture navigation for back/return actions is more natural than accessing the menu each time you want to return to the main screen.

**Describe alternatives you've considered**
The only alternative is to navigate through the app using the hamburger menu options

**Additional context**
No further info

**Comment by mistical** [comment]
I would love to see this feature brought back too. I have a huge habit of hitting the back button often and have already done it a few times since just installing the app yesterday.

Keep up the great work!

**Comment by TheMeanCanEHdian** [comment]
This is finished and will be in the next release.

**Comment by TheMeanCanEHdian** [comment]
Implemented in version 2.4.4.
