### ISSUE TITLE
Blank stream details when playing music from certain players

### ISSUE THREAD

**Issue by hdiogosilva** [Tautulli/Tautulli-Remote#92]
The details screen for music streams of certain players is completely blank (see screenshot).
+ Only seen it happen when playing music
+ I've seen this when playing from both the Plexamp desktop and android apps, as well as the android Plex app (from two different devices)
+ This does _NOT_ happen when playing music from the browser (plex.tv or my reverse proxy)
+ Nothing abnormal is shown in the logs (just the normal connection INFO level entries)

**To Reproduce**
1. Start music on a plex client (that is _not_ the web client)
2. Tap on the stream entry in the Activity tab

**Expected behavior**
Stream details as shown in the web interface & non-affected players.

**Screenshots**
<img src="https://user-images.githubusercontent.com/16733911/110474025-17c45980-80d7-11eb-94fc-02e2c96cfe11.jpg" width="300">

**Smartphone:**
 - Device: LG G6
 - OS: Android 9
 - App Version: 2.3.2

**Comment by TheMeanCanEHdian** [comment]
I was able to reproduce this issue. It was due to an empty bandwidth result. Version 2.4.1 is currently under review and has a fix.

**Comment by hdiogosilva** [comment]
Installed and confirmed working. :+1:
