### ISSUE TITLE
Blank stream details when more than 1 stream active

### ISSUE THREAD

**Issue by sterod** [Tautulli/Tautulli-Remote#93]
**Describe the bug**
See attached photos.  When more than one stream is active, the stream details of the media on the top are blank, the details for the one at the bottom are visible.

**To Reproduce**
Have more than one stream running, tap on top stream, details will be blank.

**Expected behavior**
See all stream details regardless of position.

**Screenshots**
Attached

**Smartphone (please complete the following information):**
Pixel 5, 2.3.2

![tautulli_1](https://user-images.githubusercontent.com/34377652/110480958-0e29fa00-80b5-11eb-86c6-e46ffc21d09e.png)
![tautulli-2](https://user-images.githubusercontent.com/34377652/110480951-0d916380-80b5-11eb-8b18-60f3339cf250.png)
![tautulli-3](https://user-images.githubusercontent.com/34377652/110480955-0e29fa00-80b5-11eb-8264-3de0d5f94965.png)

**Comment by TheMeanCanEHdian** [comment]
I suspect this issue is the same as #92. Version 2.4.1 is in review and contains a fix.

You can verify by checking what Tautulli shows for the bandwidth on an item where the details load in grey like that.

**Comment by TheMeanCanEHdian** [comment]
2.4.1 is now live.

**Comment by sterod** [comment]
The problem still occurs.  I now have only a single stream running (Revenge) as shown in screenshot and tapping it results in an all grey screen with just the blue view media button below.

Perhaps its something to do with the stream details specifically, as others display properly.

For reference, here are the stream details in the Tautulli web app.

![tautulli_4](https://user-images.githubusercontent.com/34377652/110488166-39641780-80bc-11eb-9ed1-653d66879dbd.JPG)

**Comment by JonnyWong16** [comment]
Something is wrong with your media info in Plex (go to the episode in Plex > click the 3 dots > view info). Try analyzing your media to get plex to update the media info. 

https://support.plex.tv/articles/200289336-analyze-media/

**Comment by sterod** [comment]
I ran the analyze media, there is no change as to how it is being displayed in the web app or tautulli remote.
Also, this media isn't recent, it's been on my PLEX for several years now.

**Comment by TheMeanCanEHdian** [comment]
Can you do the following while that item is in your activity and provide me with the output? Make sure to mask any IP/email/other sensitive info before sharing.

https://`$DOMAIN`/api/v2?apikey=`$APIKEY`&cmd=get_activity

**Comment by sterod** [comment]
I get 404 Not Found Nothing matches the given URI, I assume the domain is my domain name and port of tautulli (8181) and api key is the one found in tautulli's web interface tab

**Comment by TheMeanCanEHdian** [comment]
Yes, you might be doing something wrong there as that is the exact command used in the app to access the API.

Make sure the API is enabled in the Tautulli settings.

**Comment by JonnyWong16** [comment]
Add your HTTP root.

e.g. `/tautulli/api/v2`

**Comment by sterod** [comment]
API is enabled.
Added HTTP root.

Now I get this:

404 Not Found - The path '/home/api/v2' was not found.

Here is the URL I am pasting in the browser.  I also tried localhost, same error.
http://a282095d7387.sn.mynetname.net:8181/home/api/v2?apikey=HIDDEN&cmd=get_activity

**Comment by JonnyWong16** [comment]
This is correct:

`http://a282095d7387.sn.mynetname.net:8181/api/v2?apikey=HIDDEN&cmd=get_activity`

**Comment by sterod** [comment]
That worked, I've attached the output.
[output.txt](https://github.com/Tautulli/Tautulli-Remote/files/6110298/output.txt)

**Comment by TheMeanCanEHdian** [comment]
That output is not for the same episode you provided above. The output shows an empty container result as well.

It's probably best if you swing by the Discord for some more in-depth troubleshooting. We'd like to see Tautulli logs, the XML, and the JSON output from get_activity for the same episode.

I can also look into failing over to empty strings when no results are provided for an item which should prevent the activity details from failing in this way. But that will address a symptom, not the cause.

**Comment by sterod** [comment]
I think putting in a workaround for empty strings is best.

**Comment by TheMeanCanEHdian** [comment]
Version 2.4.2 is live with some changes on how to handle bad/missing data. If that doesn't resolve this issue feel free to re-open.

**Comment by sterod** [comment]
That worked, good job!
![Screenshot_20210309-141321](https://user-images.githubusercontent.com/34377652/110524717-beadf300-80e1-11eb-9a8b-8174d2a5940b.png)
