### ISSUE TITLE
Bandwidth Info

### ISSUE THREAD

**Issue by skubiszm** [Tautulli/Tautulli-Remote#97]
My server is bandwidth constrained, so I am always monitoring how much bandwidth is being used. On the Tautulli homepage, at the very time it shows:

ACTIVITY    Sessions: 4 streams (2 direct plays, 1 direct stream, 1 transcode) | Bandwidth: 15.1 Mbps (LAN: 10.6 Mbps, WAN: 4.5 Mbps) 

It would be amazing if this aggregate information was at the top of the Activity page on the app as well. 

As a bonus, the bandwidth for each playing item could also be shown, This would be great to see at a glance without having to click on each item for more info.

This feature doesn't exist on Plex Dash either.

**Comment by TheMeanCanEHdian** [comment]
Bandwith info will be added in the next release. The number and types of streams have not been included due to space limitations.

**Comment by TheMeanCanEHdian** [comment]
This is now live in v2.6.0+.
