### ISSUE TITLE
Enhanced User Details

### ISSUE THREAD

**Issue by DonCaliOni** [Tautulli/Tautulli-Remote#98]
Hi, on the previous version of the app, you could go into the users section, see when a user was last seen on the server, and also see their play stats (last 24 hours, 7 days, month and all time).

This is not in the new version of the app, so would be useful to have. 

Thanks

**Comment by TheMeanCanEHdian** [comment]
A user details page will be available in the next release.

**Comment by TheMeanCanEHdian** [comment]
This is now live in v2.6.0+.
