### ISSUE TITLE
Pressing the Android back button should go to the Activity page if not already there - regression from 1.x

### ISSUE THREAD

**Issue by PaarthShah** [Tautulli/Tautulli-Remote#99]
**Is your feature request related to a problem? Please describe.**
Pressing the Android back button in the (2.x) Tautulli mobile app on any page other than the Activity page currently closes the app and returns the user to the android home screen. This behavior is a regression from the 1.x mobile app.

**Describe the solution you'd like**
Pressing the back button should bring the user back to the Activity page. Pressing the back button while on the Activity page should close the app.

**Describe alternatives you've considered**
N/A

**Comment by JonnyWong16** [comment]
Duplicate #90.
